### ISSUE TITLE
[Bug] "Suspend immediately" not working, being affected by "loaded tab count"

### ISSUE THREAD

**Issue by ReporterX** [k5md/Total-Suspender-webextension#8] opened 2019-04-10 04:59 UTC
"Suspend immediately" should work once I click on it, no matter what auto-suspend settings I have.

However it is actually affected by "loaded tab count". For example, if I set it at 9, "Suspend immediately" does not work if I have 9 or fewer loaded tabs.

Thank you.

**Comment by k5md** [comment] 2019-04-10 15:53
I've checked the issue with unclear "Suspend when tabs count reach" description, so this part of the issue will be fixed, but the button "Suspend immediately" was introduced to immediately suspend tabs using current config, this is not a bug, I guess, I should better rename it for "Suspend immediately using current settings' or something shorter.
You need a functionality that ignores all settings and suspends all tabs, except for the current one? I can place other button for it.

**Comment by ReporterX** [comment] 2019-04-11 05:51
Oh I see, so it acts as a way to suspend tabs by overriding the wait settings. Your idea is great. I will use the first button most of the time. It doesn't hurt to have choices though. I would say yes if it is easy to implement.

The first button can be renamed as: 
Suspend now if criteria match

The second button can be renamed as: 
Suspend all tabs now

You have two criteria now. The time is a setting, but not a criteria, so I think "criteria" is a better word than "settings".

Thank you.

**Closed as completed** 2019-04-12 17:47 UTC
